- name: "Set collectd's config file destination"
  set_fact: >
    collectd_config_dest=/etc/collectd/collectd.conf
  tags:
    - collectd

- name: "Install required packages"
  apt : >
    name={{ item }}
    state=latest
  with_items:
    - git
    - collectd
    - collectd-core
    - collectd-utils
  tags:
    - install
    - collectd
    - pkgs

- name: "Load coretemp module on boot"
  lineinfile: >
    dest=/etc/modules
    line=coretemp
  when: monitor_coretemp
  tags:
    - collectd
    - files